name: release docker image
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
env:
  IMAGE_TAG: ghcr.io/cse3210-001-02/cse3210-container:latest
permissions:
  packages: write
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check tags
        run: |
          echo 'Current tag: ${{ github.ref_name }}'
          echo 'Current commit: ${{ github.sha }}'
      - name: build docker image
        run: |
          docker build -t ${{ env.IMAGE_TAG }} .
      - name: login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: release
        run: |
          docker push ${{ env.IMAGE_TAG }}
